# Generated by Django 6.1.1 on 2026-09-19 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('age', models.PositiveIntegerField(help_text='Вкажіть приблизний вік у повних місяцях. Наприклад, 24 – це 2 роки.', verbose_name='Вік у місяцях')),
                ('species', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кіт'), ('rabbit', 'Кролик'), ('rodent', 'Гризун'), ('bird', 'Птах'), ('other', 'Інша тварина')], default='other', max_length=50, verbose_name='Вид')),
                ('description', models.TextField(verbose_name='Опис тварини')),
                ('adoption_status', models.CharField(choices=[('available', 'Шукає домівку'), ('adopted', 'Усиновлена'), ('archived', 'В архіві')], default='available', max_length=50, verbose_name='Статус')),
                ('main_photo', models.ImageField(blank=True, upload_to='animals/', verbose_name='Фото тварини')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Додали в обране')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='shelters.shelter', verbose_name='Притулок')),
            ],
            options={
                'verbose_name': 'Тварина',
                'verbose_name_plural': 'Тварини',
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animals/gallery/', verbose_name='Фото')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animals.animal', verbose_name='Тварина')),
            ],
            options={
                'verbose_name': 'Фото тварини',
                'verbose_name_plural': 'Фотографії тварин',
            },
        ),
        migrations.CreateModel(
            name='AnimalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Текст новини')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='animals.animal', verbose_name='Тварина')),
            ],
            options={
                'verbose_name': 'Новина про тварину',
                'verbose_name_plural': 'Новини про тварин',
                'ordering': ['-created_at'],
            },
        ),
    ]
