# Generated by Django 6.1.1 on 2026-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='main_photo',
            field=models.ImageField(upload_to='animals/', verbose_name='Фото тварини'),
        ),
    ]
