# Generated by Django 6.1.1 on 2026-10-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('male', 'Хлопчик'), ('female', 'Дівчинка')], max_length=12, null=True, verbose_name='Стать'),
        ),
    ]
