# Generated by Django 6.1.1 on 2026-10-02 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='main_photo',
            field=models.ImageField(upload_to='animals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фото тварини'),
        ),
    ]
