# Generated by Django 6.1.1 on 2026-10-02 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_animal_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='image',
            field=models.ImageField(upload_to='animals/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Фото'),
        ),
    ]
