# Generated by Django 6.1.1 on 2026-09-19 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва притулку')),
                ('description', models.TextField(verbose_name='Опис притулку')),
                ('city', models.CharField(max_length=200, verbose_name='Місто')),
                ('address', models.CharField(max_length=200, verbose_name='Адреса')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=200, verbose_name='Електронна пошта')),
                ('website', models.URLField(blank=True, verbose_name='Вебсайт')),
                ('status', models.CharField(choices=[('pending', 'Очікує перевірки'), ('approved', 'Перевірений'), ('rejected', 'Перевірку не пройшов'), ('inactive', 'Неактивний')], default='pending', max_length=20, verbose_name='Статус притулку')),
                ('logo', models.ImageField(blank=True, upload_to='shelters/', verbose_name='Логотип притулку')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to=settings.AUTH_USER_MODEL, verbose_name='Власник притулку')),
            ],
            options={
                'verbose_name': 'Притулок',
                'verbose_name_plural': 'Притулки',
            },
        ),
    ]
