# Generated by Django 6.1.1 on 2026-09-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_shelter_city_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='delivery_branch',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер або адреса відділення'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='delivery_service',
            field=models.CharField(blank=True, max_length=100, verbose_name='Служба доставки'),
        ),
    ]
