# Generated by Django 6.1.1 on 2026-09-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0003_shelter_delivery_branch_shelter_delivery_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='payment_iban',
            field=models.CharField(blank=True, max_length=40, verbose_name='IBAN для переказу'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='payment_recipient',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отримувач переказу'),
        ),
    ]
