# Generated by Django 6.1.1 on 2026-10-02 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0004_shelter_payment_iban_shelter_payment_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='logo',
            field=models.ImageField(blank=True, upload_to='shelters/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Логотип притулку'),
        ),
    ]
