# Generated by Django 6.1.1 on 2026-09-19 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Мотиваційний текст')),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Схвалена'), ('rejected', 'Відхилена')], default='pending', max_length=15, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення заявки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter_comment', models.TextField(blank=True, verbose_name='Коментар від притулку')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_applications', to='animals.animal', verbose_name='Тварина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Заявка на адопцію',
                'verbose_name_plural': 'Заявки на адопцію',
                'constraints': [models.UniqueConstraint(fields=('user', 'animal'), name='unique_user_animal_application', violation_error_message='Ви вже подали заявку на цю тварину.')],
            },
        ),
    ]
