# Generated by Django 6.1.1 on 2026-10-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='shelter_notes',
            field=models.TextField(blank=True, verbose_name='Нотатки притулку'),
        ),
    ]
