# Generated by Django 6.1.1 on 2026-10-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_add_shelter_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Контактний телефон'),
        ),
    ]
