# Generated by Django 6.1.1 on 2026-09-19 09:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Потреба')),
                ('description', models.TextField(blank=True, verbose_name='Опис потреби')),
                ('category', models.CharField(choices=[('food', 'Їжа'), ('medicine', 'Ліки'), ('treatment', 'Лікування'), ('care', 'Догляд'), ('other', 'Інше')], default='other', max_length=100, verbose_name='Категорія потреби')),
                ('frequency', models.CharField(choices=[('one_time', 'Одноразово'), ('monthly', 'Щомісяця')], default='one_time', max_length=20, verbose_name='Періодичність допомоги')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цільове значення')),
                ('unit', models.CharField(choices=[('money', 'грн'), ('weight', 'кг'), ('quantity', 'шт')], max_length=20, verbose_name='Одиниця вимірювання')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус потреби')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='needs', to='animals.animal', verbose_name='Тварина')),
            ],
            options={
                'verbose_name': 'Потреба тварини',
                'verbose_name_plural': 'Потреби тварин',
            },
        ),
        migrations.CreateModel(
            name='SupportContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Обсяг допомоги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Внесок підтверджено')),
                ('proof', models.ImageField(blank=True, upload_to='contributions/proofs/', verbose_name='Фото підтвердження допомоги')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='support.need', verbose_name='Потреба')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Благодійник')),
            ],
            options={
                'verbose_name': 'Благодійний внесок',
                'verbose_name_plural': 'Благодійні внески',
            },
        ),
    ]
