# Generated by Django 6.1.1 on 2026-09-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcontribution',
            name='proof',
            field=models.ImageField(upload_to='contributions/proofs/', verbose_name='Фото підтвердження допомоги'),
        ),
    ]
