# Generated by Django 6.1.1 on 2026-09-25 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_supportcontribution_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcontribution',
            name='proof',
            field=models.FileField(upload_to='contributions/proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Фото підтвердження допомоги'),
        ),
    ]
