# Generated by Django 6.1.1 on 2026-10-01 16:10

import django.core.validators
from django.db import migrations, models

def copy_approval(apps, schema_editor):
    Contribution = apps.get_model('support', 'SupportContribution')
    Contribution.objects.using(schema_editor.connection.alias).filter(
        is_approved=True
    ).update(status='approved')

class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_supportcontribution_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcontribution',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Очікує перевірки'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')],
                default='pending', max_length=30, verbose_name='Статус внеску'),
        ),
        migrations.RunPython(copy_approval),
        migrations.RemoveField(
            model_name='supportcontribution',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='supportcontribution',
            name='proof',
            field=models.FileField(upload_to='contributions/proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Файл підтвердження допомоги'),
        ),
    ]
