# Generated by Django 6.1.1 on 2026-10-02 07:04

import django.core.validators
import support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_contribution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcontribution',
            name='proof',
            field=models.FileField(storage=support.models.private_proof_storage, upload_to='contributions/proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Файл підтвердження допомоги'),
        ),
    ]
